# Workflow meant to be used by external repositories
# that are configured with this `meta` repository
name: Coverage
on:
  # allow this workflow to be called
  # by other workflows from other repositories
  workflow_call:
    inputs:
      os-packages:
        required: false
        type: string

jobs:
  test:
    name: Coverage report
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: ["3.11"]
        os: ["ubuntu-latest"]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install OS packages
        if: inputs.os-packages != ''
        run: sudo apt-get install -y ${{ inputs.os-packages }}
      - name: Cache packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('tox.ini') }}
          restore-keys: |
            ${{ runner.os }}-pip-${{ matrix.python-version }}-
            ${{ runner.os }}-pip-
      - name: Install dependencies
        run: python -m pip install tox
      - name: Initialize tox
        run: |
          if [ `tox list --no-desc -f init|wc -l` = 1 ]; then tox -e init;else true; fi
      - name: Run coverage
        run: |
          tox -q -e coverage >> $GITHUB_STEP_SUMMARY
